defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *defaults
  database: mysql_perf_development

test:
  <<: *defaults
  database: mysql_perf_test

production:
  <<: *defaults
  database: mysql_perf_production
